env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -X github.com/admiralobvious/password/cmd.version={{.Version}}
  - -X github.com/admiralobvious/password/cmd.commit={{.ShortCommit}}
  - -X github.com/admiralobvious/password/cmd.date={{.Date}}
  goarch:
    - amd64
dockers:
  - image_templates:
      - "admiralobvious/password:{{ .Tag }}"
      - "admiralobvious/password:v{{ .Major }}"
      - "admiralobvious/password:v{{ .Major }}.{{ .Minor }}"
      - "admiralobvious/password:latest"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
